--- BD Postgres(Supabase)

create table maquinas(
  id_maquina bigint generated by default as identity primary key,
  modelo text not null,
  marca text,
  ano int
);

create table talhoes(
  id_talhoes bigint generated by default as identity primary key,
  nome text not null,
  area_ha decimal(10,2) not null,
  tipo_solo text
);

create table telemetria_maquinas(
  id_telemetria_maq bigint generated by default as identity primary key,
  maquina_id int references maquinas(id_maquina) on delete cascade,
  timestamp timestamptz default now(),
  latitude numeric(9,6),
  longitude numeric(9,6),
  velocidade_kmh numeric(5,2),
  consumo_h numeric(5,2),
  umidade_grao numeric(5,2)
);

create table sensores_solo (
  id_sensor bigint generated by default as identity primary key,
  talhoes_id int references talhoes(id_talhoes),
  timestamp timestamp default now(),
  umidade_percent decimal (5,2)
);

create table colheitas (
  id_colheita bigint generated by default as identity primary key,
  talhoes_id int references talhoes(id_talhoes),
  safra numeric(4),
  peso_kg decimal (15,2)
);
